baseURL = "https://alisonschultz.github.io/"
languageCode = "en-us"
title = "Alison Schultz"
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

pygmentsUseClasses = true

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  description = "Alison Schultz — financial economist at the Tax Justice Network."
  author = "Alison Schultz"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowRssButtonInSectionTermList = false
  ShowToc = false
  disableSpecial1stPost = true
  disableScrollToTop = true
  comments = false
  hidemeta = true
  hideSummary = false

  [params.profileMode]
    enabled = true
    title = "Alison Schultz"
    subtitle = "I am a financial economist at the Tax Justice Network. My research interests include the real effects of financial markets, financial crime, corporate taxation, wealth taxes, and tax abuse."
    imageUrl = "Schultz_Alison_4052.jpg"
    imageWidth = 220
    imageHeight = 280
    imageTitle = "Alison Schultz"

    [[params.profileMode.buttons]]
      name = "Research"
      url = "research"

    [[params.profileMode.buttons]]
      name = "Policy"
      url = "policy"

    [[params.profileMode.buttons]]
      name = "Media"
      url = "media"

    [[params.profileMode.buttons]]
      name = "CV"
      url = "Schultz_CV.pdf"

  [params.assets]
    disableHLJS = true
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:alison@taxjustice.net"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/alisonschultz"

  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=-fYziBEAAAAJ&hl=en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
